# Read the Docs configuration file for pyKOSMOS++
# Author: Gourav Khullar
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - htmlzip
  - epub

# Python configuration
python:
  version: "3.10"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - echo "Installing dependencies..."
    post_build:
      - echo "Build complete!"

# Submodules
submodules:
  include: []
  recursive: false
